# .github/release.yml

changelog:
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: Enhancements 🎉
      labels:
        - enhancement
    - title: Bugs 🐛
      labels:
        - bug
    - title: Dependency Upgrades ⬆
      labels:
        - dependencies
    - title: Other Changes
      labels:
        - "*"
